### ISSUE TITLE
Can not clone and run the project

### ISSUE THREAD

**Issue by bobhu1** [UmTemplates/UmBootstrap#236]
Try to clone the project from github use visual studio 2022, after clone trying to run the project got following error:

An unhandled exception occurred while processing the request.
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.
Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)

Show raw exception details:
Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.
   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)
   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by deanleigh** [comment]
Hi @bobhu1
do you want to use the starter kit to create a website with examples or do you want to contribute?

**Comment by bobhu1** [comment]
Thanks a lot, I am new with Umbraco and trying to create a website with the
start kit, also just want to know if the start kit comes with a login and
registration form?


Thanks again.

**Comment by deanleigh** [comment]
Hey @bobhu1,
ahh in that case you should use the dotnet new command:
[https://marketplace.umbraco.com/package/umbraco.community.templates.umbootstrap](https://marketplace.umbraco.com/package/umbraco.community.templates.umbootstrap)
