### ISSUE TITLE
Namespace errors for Home and WebPage

### ISSUE THREAD

**Issue by deanleigh** [UmTemplates/UmBootstrap#88]
![image](https://github.com/Umbootstrap/Umbootstrap/assets/6745929/185268f4-e1a8-4d32-8981-bb413b838292)
Do we need both:
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Cms.Web.Common.PublishedModels;

**Comment by SimonAntony** [comment]
@deanleigh No we dont, basically the @using ContentModels option just provides a shortcut and cleans up the code in the view instead of using the long name version.

**Comment by deanleigh** [comment]
Now we are using Models builder which @using should we use?

**Comment by SimonAntony** [comment]
I would use @using ContentModels = Umbraco.Cms.Web.Common.PublishedModels; for clarity
